image:
  - Visual Studio 2022

environment:
  nodejs_version: "20"

branches:
  only:
    - master  # ветка git
    - main

cache: #node_modules  # кеширование

install:
    # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm test --passWithNoTests # скрипт тестирования
